### ISSUE TITLE
Change Chat Wars bot name

### ISSUE THREAD

**Issue by MikalaiSivokha** [3mph4515/Chat-Wars-Ratings-Bot#11]
RU Chat Wars bot is going to move to the new bot name:
- https://t.me/chatwars/116

Please change bot to parse messages from @ChatWarsClassicBot instead of @ChatWarsBot

**Comment by MikalaiSivokha** [comment]
Fixed in pull request https://github.com/3mph4515/Chat-Wars-Ratings-Bot/pull/12

**Comment by 3mph4515** [comment]
Cool 👍
