### ISSUE TITLE
Change instruction message after the bot has received /top forward

### ISSUE THREAD

**Issue by MikalaiSivokha** [3mph4515/Chat-Wars-Ratings-Bot#6]
When user has sent forward of the /top command from the @ChatWarsBot he gets instruction to use /top command but it doesn't supported.
![image](https://user-images.githubusercontent.com/5271230/32937633-622b9fca-cb8a-11e7-99d0-4730c1ab218b.png)

**Comment by MikalaiSivokha** [comment]
Fixed in https://github.com/3mph4515/Chat-Wars-Ratings-Bot/commit/0da4ec04c2d8fda828e64e16a71a5f8ecdc2873e

**Comment by 3mph4515** [comment]
Also, need to notify the user about our new mega superb website.
